Vagrant.configure("2") do |config|
config.vm.box = "debian/buster64"

config.vm.provider "virtualbox" do |v|
  v.cpus = 1
  v.memory = "512"
end

config.vm.provision "shell", inline: <<-SHELL
  apt update
SHELL


config.vm.define "master" do |m|
  m.vm.hostname = "master"
  m.vm.network :private_network, :ip => "192.168.56.10"
  curl -sfL https://get.k3s.io | sh -s
end

config.vm.define "node1" do |n|
  n.vm.hostname = "node1"
  n.vm.network :private_network, :ip => "192.168.56.20"
end

config.vm.define "node2" do |w|
  w.vm.hostname = "node2"
  w.vm.network :private_network, :ip => "192.168.56.30"
end
end
